[formatter.nixfmt]
command = "nixfmt"
includes = ["**/*.nix"]

[formatter.lua]
command = "stylua"
includes = ["**/*.lua"]

[formatter.taplo]
command = "taplo"
options = ["fmt"]
includes = ["**/*.toml"]

[formatter.oxfmt]
command = "oxfmt"
includes = ["**/*.md", "**/*.yaml", "**/*.yml"]