sync:
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
	
	ln -s ${PWD}/zshenv ~/.zshenv
	ln -s ${PWD}/zshrc ~/.zshrc

delete:
	rm -f ~/.zshenv
	rm -f ~/.zshrc
